on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 18
      - run: yarn install
      - run: yarn run lint:check
      - run: yarn run build
      - run: npm test
      - name: Upload coverage reports to Codecov
        uses: step-security/codecov-action@87e66f47a0f8ab4cae465a323eb9ec63d8b6b875 # v6.0.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
