on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Create .npmrc file
        run: |
          echo "@:registry=https://npm.pkg.github.com \
          @MAD-Goat-Project:registry=https://npm.pkg.github.com \
          //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"  > .npmrc
      - run: yarn install
      - run: yarn run lint:check
      - run: yarn run build
      - run: npm test
